services:
  database:
    image: 'postgres:16'
    hostname: 'database'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tv_backend_development
    volumes:
      - ~/.db-data/tv_backend_development:/var/lib/postgresql/data/

  backend:
    build:
      dockerfile: ./Dockerfile
    hostname: 'backend'
    ports:
      - 1337:1337
    environment:
      RAILS_ENV: development
    develop:
      watch:
        - path: ./app/
          target: /opt/tvbackend/app/
          action: sync
        - path: Gemfile
          action: rebuild
    depends_on:
      - database
