services:
  database:
    image: 'postgres:16'
    ports:
      - 5432:5432
    networks:
      devnet:
        ipv4_address: 10.10.10.2
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tv_backend_dev
    volumes:
      - ~/.db-data/tv_backend_development:/var/lib/postgresql/data/

  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 1337:1337
    networks:
      devnet:
        ipv4_address: 10.10.10.3
    develop:
      watch:
        - path: ./app/
          target: /opt/tvbackend/app/
          action: sync
        - path: Gemfile
          action: rebuild
    volumes:
      - ~/.rail-data/tv_backend/:/opt/tvbackend
    depends_on:
      - database

networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
